### PR TITLE
Introducing a --host option to allow using (n) subdomains

### LINKED ISSUE #31: Only support top level  domain
It not works when host domain is not top level domain. I want to use subdomain as base domain described in https://github.com/localtunnel/server#use-your-server, such as `subdomain.example.com` and `*.subdomain.example.com`. This issue is similar to #21.

### PR DESCRIPTION
**Pull request by manuelbieh**
Fixes #31 

Example usage:
`$ node bin/server --port 1234 --host multi.levels.deep.mydomain.com`

Client:

```
$ lt --port 80 --host http://multi.levels.deep.mydomain.com:1234
your url is: http://ypxwyyefij.multi.levels.deep.mydomain.com:1234
```

Also allows usage of sub-sub[-sub[...]] domains:
`$ node bin/server --port 1234 --host levels.deep.mydomain.com`

Client:

```
$ lt --port 80 --host http://levels.deep.mydomain.com --subdomain one.two
your url is: http://one.two.levels.deep.mydomain.com:1234
```

Possible usecase (my particular case): debugging of "customer specific subdomain webapps" on a developer machine running localtunnel (_exampleproject.manuel.tunnelserver.company.org_). tunnelserver.company.org would be the tunnel server's url and `exampleproject.manuel` a custom subdomain pointing to a very specific project on my machine.

Imagine you needed access to a specific team on Slack (_teamname.slack.com_) on a developer's local machine (_teamname.manuelsmachine.slack.com_) from outside via localtunnel on a company's dev domain (_teamname.manuelsmachine.localtunnel.slack.com_). It would be as simple as `node bin/server --host localtunnel.slack.com` and `lt --port 80 --host http://localtunnel.slack.com --subdomain teamname.manuelsmachine`

_(I'm not working for Slack, just using it as example since everybody knows the pattern behind Slack's URLs)_

### CODE REVIEW

**Comment by mskims** [comment]
i made docker file for this pr.
https://hub.docker.com/r/ohwhos/localtunnel-server/

**Comment by zodman** [comment]
im testings and works +1

**Comment by zzh8829** [comment]
is anyone still working on this PR ?

**Comment by zodman** [comment]
the PR works!

**Comment by manuelbieh** [comment]
Looks like we're having a conflict here.

**Comment by whitecolor** [comment]
@defunctzombie will you merge an publish new version with docker image please?

**Comment by arthot** [comment]
@manuelbieh, please, resolve so simple conflict on empty lines, otherwise this PR will stuck for another year :man_facepalming:

**Comment by arthot** [comment]
@manuelbieh, you are :rocket:. Resolved in 5 minutes :+1: 
@defunctzombie, now it's your turn. Please, merge this PR. One year of waiting.. It can close at least 4 issues #31, #51, #13, #40

**Comment by manuelbieh** [comment]
I usually respond within 5 minutes or never 😁 😉

**Comment by whitecolor** [comment]
BTW I've made alternative implementation of this feature, some may check if needed https://github.com/localtunnel/server/pull/65

**Comment by chmduquesne** [comment]
When is this feature going to be integrated?

**Comment by taniki** [comment]
Using this PR. I now have a new error when trying to get a tunnel

```
  localtunnel server listening on port: 3000 +0ms
  localtunnel:server request /?new +1m
[error]	bookrc.js:10 Assignment to constant variable.
TypeError: Assignment to constant variable.
    at maybe_bounce (server.js:59:9)
    at Server.<anonymous> (server.js:330:52)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:546:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
TypeError: Assignment to constant variable.
    at maybe_bounce (server.js:59:9)
    at Server.<anonymous> (server.js:330:52)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:546:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
```

node version : 6.9.1

**Comment by whitecolor** [comment]
@taniki try this one https://github.com/localtunnel/server/pull/65

**Comment by defunctzombie** [comment]
Closing in favor of #65. Will evaluate that PR as a potential enhancement.

**Pull request closed without merging**
